// flow-typed signature: 6539f9c8dacc770a4f415387351935cc
// flow-typed version: <<STUB>>/soap_v^0.25.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'soap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'soap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'soap/lib/client' {
  declare module.exports: any;
}

declare module 'soap/lib/http' {
  declare module.exports: any;
}

declare module 'soap/lib/nscontext' {
  declare module.exports: any;
}

declare module 'soap/lib/security/BasicAuthSecurity' {
  declare module.exports: any;
}

declare module 'soap/lib/security/BearerSecurity' {
  declare module.exports: any;
}

declare module 'soap/lib/security/ClientSSLSecurity' {
  declare module.exports: any;
}

declare module 'soap/lib/security/ClientSSLSecurityPFX' {
  declare module.exports: any;
}

declare module 'soap/lib/security/index' {
  declare module.exports: any;
}

declare module 'soap/lib/security/NTLMSecurity' {
  declare module.exports: any;
}

declare module 'soap/lib/security/WSSecurity' {
  declare module.exports: any;
}

declare module 'soap/lib/security/WSSecurityCert' {
  declare module.exports: any;
}

declare module 'soap/lib/server' {
  declare module.exports: any;
}

declare module 'soap/lib/soap' {
  declare module.exports: any;
}

declare module 'soap/lib/utils' {
  declare module.exports: any;
}

declare module 'soap/lib/wsdl' {
  declare module.exports: any;
}

declare module 'soap/soap-stub' {
  declare module.exports: any;
}

// Filename aliases
declare module 'soap/index' {
  declare module.exports: $Exports<'soap'>;
}
declare module 'soap/index.js' {
  declare module.exports: $Exports<'soap'>;
}
declare module 'soap/lib/client.js' {
  declare module.exports: $Exports<'soap/lib/client'>;
}
declare module 'soap/lib/http.js' {
  declare module.exports: $Exports<'soap/lib/http'>;
}
declare module 'soap/lib/nscontext.js' {
  declare module.exports: $Exports<'soap/lib/nscontext'>;
}
declare module 'soap/lib/security/BasicAuthSecurity.js' {
  declare module.exports: $Exports<'soap/lib/security/BasicAuthSecurity'>;
}
declare module 'soap/lib/security/BearerSecurity.js' {
  declare module.exports: $Exports<'soap/lib/security/BearerSecurity'>;
}
declare module 'soap/lib/security/ClientSSLSecurity.js' {
  declare module.exports: $Exports<'soap/lib/security/ClientSSLSecurity'>;
}
declare module 'soap/lib/security/ClientSSLSecurityPFX.js' {
  declare module.exports: $Exports<'soap/lib/security/ClientSSLSecurityPFX'>;
}
declare module 'soap/lib/security/index.js' {
  declare module.exports: $Exports<'soap/lib/security/index'>;
}
declare module 'soap/lib/security/NTLMSecurity.js' {
  declare module.exports: $Exports<'soap/lib/security/NTLMSecurity'>;
}
declare module 'soap/lib/security/WSSecurity.js' {
  declare module.exports: $Exports<'soap/lib/security/WSSecurity'>;
}
declare module 'soap/lib/security/WSSecurityCert.js' {
  declare module.exports: $Exports<'soap/lib/security/WSSecurityCert'>;
}
declare module 'soap/lib/server.js' {
  declare module.exports: $Exports<'soap/lib/server'>;
}
declare module 'soap/lib/soap.js' {
  declare module.exports: $Exports<'soap/lib/soap'>;
}
declare module 'soap/lib/utils.js' {
  declare module.exports: $Exports<'soap/lib/utils'>;
}
declare module 'soap/lib/wsdl.js' {
  declare module.exports: $Exports<'soap/lib/wsdl'>;
}
declare module 'soap/soap-stub.js' {
  declare module.exports: $Exports<'soap/soap-stub'>;
}
